# Generated by Django 3.2.9 on 2021-11-13 00:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('day_planer', '0003_alter_note_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 0, 42, 44, 735056, tzinfo=utc), verbose_name='Creation time'),
        ),
    ]
